export const GALLERY_ITEMS = [
  {
    id: "gallery-milkshakes",
    categoryId: "milkshakes",
    label: "Milkshakes",
    featuredProduct: "Planet Shakes L",
    featuredPrice: 6.99,
    src: "/images/categories/milkshakes.jpg",
    alt: "Chocolate milkshake topped with whipped cream, chocolate drizzle and an Oreo cookie",
    width: 682,
    height: 1024,
  },
  {
    id: "gallery-brownies",
    categoryId: "brownies",
    label: "Brownies",
    featuredProduct: "Kinder Bueno Brownie",
    featuredPrice: 4.99,
    src: "/images/categories/brownies.jpg",
    alt: "Warm chocolate brownie with vanilla ice cream, chocolate sauce and almond flakes",
    width: 1024,
    height: 682,
  },
  {
    id: "gallery-cakes",
    categoryId: "cakes",
    label: "Cakes",
    featuredProduct: "Red Velvet Cake",
    featuredPrice: 4.99,
    src: "/images/categories/cakes.jpg",
    alt: "Rich chocolate celebration cake with cherries and chocolate sprinkles",
    width: 1024,
    height: 821,
  },
  {
    id: "gallery-donuts",
    categoryId: "donuts",
    label: "Donuts",
    featuredProduct: "Oh So Oreo Donut",
    featuredPrice: 2.5,
    src: "/images/categories/donuts.jpg",
    alt: "Chocolate glazed donut with white chocolate drizzle and crushed pistachios",
    width: 682,
    height: 1024,
  },
  {
    id: "gallery-pancakes",
    categoryId: "american-pancakes",
    label: "American Pancakes",
    featuredProduct: "Ferrero Fantasy American Pancakes",
    featuredPrice: 7.99,
    src: "/images/categories/american-pancakes.jpg",
    alt: "Stack of golden pancakes drizzled with rich dark chocolate sauce",
    width: 1024,
    height: 682,
  },
  {
    id: "gallery-waffles",
    categoryId: "waffles",
    label: "Waffles",
    featuredProduct: "Planet Special",
    featuredPrice: 8.99,
    src: "/images/categories/waffles.jpg",
    alt: "Belgian waffles topped with cream, fresh blueberries and powdered sugar",
    width: 1024,
    height: 682,
  },
  {
    id: "gallery-sundaes",
    categoryId: "sundaes",
    label: "Sundaes",
    featuredProduct: "Brownie Kunafa",
    featuredPrice: 7.99,
    src: "/images/categories/sundaes.jpg",
    alt: "Berry sundae with soft serve, fresh strawberries and raspberry sauce",
    width: 1024,
    height: 768,
  },
  {
    id: "gallery-mocktails",
    categoryId: "mocktails",
    label: "Mocktails",
    featuredProduct: "Mango Passion",
    featuredPrice: 4.99,
    src: "/images/categories/mocktails.jpg",
    alt: "Refreshing mojito mocktail with lime, mint and crushed ice",
    width: 682,
    height: 1024,
  },
  {
    id: "gallery-gelato",
    categoryId: "gelato",
    label: "Gelato",
    featuredProduct: "3 Scoops Gelato",
    featuredPrice: 4.99,
    src: "/images/categories/gelato.jpg",
    alt: "Assorted gelato scoops in waffle cones on display",
    width: 1024,
    height: 682,
  },
];
